---
core:
  ADMINUSER: admin
  AGUADIR: agua
  AGUAUSER: agua
  EXECUTION_TEMPDIR: /tmp
  INSTALLDIR: /home/stuart.young/flow
  TEMPDIR: /tmp
  USERDIR: /home
  SCHEDULER: local
scheduler:
  CANCELJOB: '/nfs/univa/bin/lx-amd64/qdel -j'
  QSTAT: /nfs/univa/bin/lx-amd64/qstat
  QSUB: /nfs/univa/bin/lx-amd64/qsub
  QUEUE: regular.q
  SGEBIN: /nfs/univa/bin/lx-amd64
  SGEEXECDPORT: '6445'
  SGEQMASTERPORT: '6444'
  SGEROOT: /nfs/univa
  SLEEP: '5'
database:
  DATABASE: agua
  DBFILE: db/agua.sqlite
  DBTYPE: SQLite
  DUMPFILE: bin/sql/dump/agua.dump
  GUESTPASSWORD: guest
  GUESTUSER: guest
  MYSQLDATA: /var/lib/mysql
  PASSWORD: xxxxxxxxxx
  SESSIONTIMEOUT: '24'
  TESTDATABASE: aguatest
  TESTDBFILE: db/test.sqlite
  TESTDBTYPE: SQLite
  TESTPASSWORD: xxxxxxxxxxx
  TESTSESSIONID: xxxxxxxxxxx
  TESTUSER: testuser
  USER: agua
